### PR TITLE
chore: update dependencies

### PR DESCRIPTION
**Pull request by paulbutcher**
Building this project results in a lot of warnings. They probably aren't too big a deal, but 
it's nice to be warning clean. I've tried updating everything to the latest, and it all still
seems to work.

There are still a couple of warnings from `npm audit`, but these are associated with an 
outstanding problem with `react-scripts`. I've moved `react-scripts` to `devDependencies` and 
everything is warning clean when they're omitted:

```
% npm audit --omit=dev  
found 0 vulnerabilities
```

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Thanks-- Ill try it locally. 

Can you add yourself to `AUTHORS.md`? :)

(Yes, we do that for every project, I know...)

**Comment by magnus-madsen** [comment]
Oh- and did you check with a complete `Data.js`?

**Comment by magnus-madsen** [comment]
I see that the build fails. Maybe that can be fixed?

**Comment by paulbutcher** [comment]
Will do on `Authors.md` and yes, I did check with a complete `Data.js`.

It builds successfully for me locally: will try to work out why it's not building in CI.

**Comment by paulbutcher** [comment]
I think I've fixed this now: it was caused by a warning with Bootstrap 5.1.3:

https://github.com/twbs/bootstrap/issues/36259

**Comment by magnus-madsen** [comment]
> I think I've fixed this now: it was caused by a warning with Bootstrap 5.1.3:
> 
> [twbs/bootstrap#36259](https://github.com/twbs/bootstrap/issues/36259)

Ill check tomorrow or sunday. I am off to bed :)

**Comment by magnus-madsen** [comment]
Thanks!

**Pull request merged**
