### PR TITLE
feat: add basic filtering

### PR DESCRIPTION
**Pull request by paulbutcher**
This PR adds very basic filtering (searching) to api.flix.dev. Some kind of more detailed 
search functionality would be nice, but this is better than nothing!

### CODE REVIEW

**Comment by magnus-madsen** [comment]
Cool! Do you have a screenshot? :)

**Comment by magnus-madsen** [comment]
"How" does it filter? What if I type `"map"`?

**Comment by paulbutcher** [comment]
This happens:

Screenshot 2022-06-03 at 22 08 35

**Comment by paulbutcher** [comment]
This happens:

Screenshot 2022-06-03 at 22 08 35

**Comment by magnus-madsen** [comment]
Cool, I'll look at the code tomorrow. Any styling we should apply to the search box?

**Comment by paulbutcher** [comment]
> Any styling we should apply to the search box?

Happy to follow your guidance here (styling isn't my strong point!)

**Comment by magnus-madsen** [comment]
> > Any styling we should apply to the search box?
> 
> Happy to follow your guidance here (styling isn't my strong point!)

Hah, me neither. I will see if bootstrap (reactstrap?) has some css class we should use.

**Comment by magnus-madsen** [comment]
Thanks! Deployed :) (force refresh may be required).

**Pull request merged**
